# Generated by Django 6.0.4 on 2026-04-25 19:52

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=users.models.get_rendom_image, upload_to='profile_pics'),
        ),
    ]
